# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fosterHome.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("fosterHome.proto", :syntax => :proto3) do
    add_message "Obn.Service.FosterHome.FosterHome" do
      optional :name, :string, 1
      optional :address, :string, 2
      optional :city, :string, 3
      optional :postalCode, :string, 4
      optional :state, :string, 5
      optional :phoneNumber, :string, 6
      optional :eMail, :string, 7
    end
  end
end

module Obn
  module Service
    module FosterHome
      FosterHome = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Obn.Service.FosterHome.FosterHome").msgclass
    end
  end
end
