# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foster_home.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("foster_home.proto", :syntax => :proto3) do
    add_message "Obn.Service.FosterHome.FosterHomeRequest" do
      optional :id, :int64, 1
      optional :filter, :string, 2
    end
    add_message "Obn.Service.FosterHome.FosterHome" do
      optional :id, :int64, 1
      optional :name, :string, 2
      optional :address, :string, 3
      optional :city, :string, 4
      optional :postalCode, :string, 5
      optional :state, :string, 6
      optional :phoneNumber, :string, 7
      optional :eMail, :string, 8
    end
  end
end

module Obn
  module Service
    module FosterHome
      FosterHomeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Obn.Service.FosterHome.FosterHomeRequest").msgclass
      FosterHome = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Obn.Service.FosterHome.FosterHome").msgclass
    end
  end
end
