# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: foster_home.proto for package 'Obn.Service.FosterHome'

require 'grpc'
require 'obn/service/foster_home/foster_home_pb'

module Obn
  module Service
    module FosterHome
      module FosterHomeService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'Obn.Service.FosterHome.FosterHomeService'

          rpc :get, ::Obn::Service::FosterHome::FosterHomeRequest, ::Obn::Service::FosterHome::FosterHome
          rpc :save, ::Obn::Service::FosterHome::FosterHome, ::Google::Protobuf::Empty
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
